### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Renjjjjjj** [Daisy-zzz/HierCas#1]
作者您好，我拜读了您的论文，想要复现一下，但我现在没有申请到APS数据集，如果方便的话，您能发我一份吗？非常感谢！innerB35674@163.com

**Comment by Daisy-zzz** [comment]
您好，由于作者目前已经毕业了，并没有保留原始数据集，APS数据集等一段时间官方就会回复的

**Comment by Renjjjjjj** [comment]
好的好的了解了，十分感谢您的回复！
















在 2024-08-12 10:58:36，"Daisy" ***@***.***> 写道：

您好，由于作者目前已经毕业了，并没有保留原始数据集，APS数据集等一段时间官方就会回复的
